# Config file for automatic testing at travis-ci.org

sudo: false
language: python
install: pip install tox coveralls
script: tox
env:
  # - TOXENV=py27-django18
  - TOXENV=py34-django18
  # - TOXENV=docs
  - TOXENV=flake8
  - TOXENV=coverage
addons:
  postgresql: "9.4"
after_success: coveralls
